### PR TITLE
Add a test which ensures ranges are up to date

### PR DESCRIPTION
**Pull request by paulmelnikow**
Hi! I was thinking about using this package, and since it hadn't been updated in a while I wanted to make sure the Cloudflare advertised ranges were up to date. It looks like they are! 😁 

Though it's easy to run this locally to check that things are up to date, running it daily in CI would be even better.

### CODE REVIEW

**Comment by cchan** [comment]
Sure yeah sounds good! I think the solution suggested in the README is generally better though:
```
const cloudflareIp = require('cloudflare-ip');

app.set('trust proxy', ip => {
  if(ip.startsWith('::ffff:'))
    ip = ip.substr(7);
  return ip == '127.0.0.1' || cloudflareIp(ip);
});
```

**Comment by cchan** [comment]
Sure yeah sounds good! I think the solution suggested in the README is generally better though:
```
const cloudflareIp = require('cloudflare-ip');

app.set('trust proxy', ip => {
  if(ip.startsWith('::ffff:'))
    ip = ip.substr(7);
  return ip == '127.0.0.1' || cloudflareIp(ip);
});
```

**Comment by cchan** [comment]
added you as a collaborator if you want to do it :P

**Comment by paulmelnikow** [comment]
Thanks for adding me!

In terms of that alternative solution, the `cloudflare-ip` package is marked deprecated.

I’m using this for badges/shields#5666 which is using a legacy framework, so I can’t use trust proxy.

Do you want to maintain a function here that’s compatible with trust proxy, either in addition to or in place of the middleware?

We’re having to shim `req.ip = req.socket.remoteAddress` to make this work, which isn’t ideal.

**Comment by cchan** [comment]
feel free to add it :) that would be super cool if there's a less hacky way.

**Pull request merged**
